---
language: java
jdk: "oraclejdk8"

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

install:
  - sudo apt-get install python-pip
  - sudo pip install ansible

  # Add ansible.cfg to pick up roles path.
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

script:
  - cat ansible.cfg
  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check
  - ansible-playbook -i tests/inventory tests/test.yml --connection=local --become

  # Verify contents of keystore
  - > 
    keytool -list -v -keystore /tmp/testCA/keystore -storepass unsecure
    | grep -q 'testservice'
    && (echo 'testservice certificate exists: pass' && exit 0)
    || (echo 'testservice certificate exists: fail' && exit 1)
  - >
    keytool -list -v -keystore /tmp/testCA/keystore -storepass unsecure
    | grep -q '1 entry'
    && (echo 'assert 1 entry exists: pass' && exit 0)
    || (echo 'assert 1 entry exists: fail' && exit 1)
  - >
    keytool -list -v -keystore /tmp/testCA/keystore -storepass unsecure
    | grep -q 'CN=testservice'
    && (echo 'assert CN is testservice: pass' && exit 0)
    || (echo 'assert CN is testservice: fail' && exit 1)
  - >
    keytool -list -v -keystore /tmp/testCA/keystore -storepass unsecure
    | grep -q 'OU=blog'
    && (echo 'assert OU is blog: pass' && exit 0)
    || (echo 'assert OU is blog: fail' && exit 1)
  - >
    keytool -list -v -keystore /tmp/testCA/keystore -storepass unsecure
    | grep -q 'O=thecuriousdev'
    && (echo 'assert O is thecuriousdev: pass' && exit 0)
    || (echo 'assert O is thecuriousdev: fail' && exit 1)
  - >
    keytool -list -v -keystore /tmp/testCA/keystore -storepass unsecure
    | grep -q 'L=Grondal'
    && (echo 'assert L is Grondal: pass' && exit 0)
    || (echo 'assert L is Grondal: fail' && exit 1)
  - >
    keytool -list -v -keystore /tmp/testCA/keystore -storepass unsecure
    | grep -q 'ST=Stockholm'
    && (echo 'assert ST is Stockholm: pass' && exit 0)
    || (echo 'assert ST is Stockholm: fail' && exit 1)
  - >
    keytool -list -v -keystore /tmp/testCA/keystore -storepass unsecure
    | grep -q 'C=SE'
    && (echo 'assert C is SE: pass' && exit 0)
    || (echo 'assert C is SE: fail' && exit 1)
  - >
    keytool -list -v -keystore /tmp/testCA/keystore -storepass unsecure
    | grep -q 'Issuer: CN=thecuriousdev.org'
    && (echo 'assert Issuer CN is thecuriousdev.org: pass' && exit 0)
    || (echo 'assert Issuer CN is thecuriousdev.org: fail' && exit 1)
  - >
    keytool -list -v -keystore /tmp/testCA/keystore -storepass unsecure
    | grep -q 'DNSName: testservice'
    && (echo 'assert testservice SAN DNS is added: pass' && exit 0)
    || (echo 'assert testservice SAN DNS is added: fail' && exit 1)
  - >
    keytool -list -v -keystore /tmp/testCA/keystore -storepass unsecure
    | grep -q 'DNSName: localhost'
    && (echo 'assert localhost SAN DNS is added: pass' && exit 0)
    || (echo 'assert localhost SAN DNS is added: fail' && exit 1)
  - >
    keytool -list -v -keystore /tmp/testCA/keystore -storepass unsecure
    | grep -q 'IPAddress: 127.0.0.1'
    && (echo 'assert 127.0.0.1 SAN IP is added: pass' && exit 0)
    || (echo 'assert 127.0.0.1 SAN IP is added: fail' && exit 1)