---
- name: ensure {{ required_pip_libs | join(', ') }} is installed
  pip: { name: "{{ required_pip_libs }}", state: present, extra_args: --user }

- name: clean up from previous run
  file: path={{ ca_path }} state=absent

- name: ensure CA path exists - {{ ca_path }}
  file: path={{ ca_path }} state=directory

- name: ensure required folders exists
  file: path={{ ca_path }}/{{ item }} state=directory
  with_items:
    - newcerts

- name: ensure service folders exists
  file: path={{ ca_path }}/{{ item.name }} state=directory
  with_items:
    - "{{ services }}"

- name: Ensure index.txt exists
  file: path={{ ca_path }}/index.txt state=touch

- name: Echo 1000 into serial
  shell: echo 1000\n > {{ ca_path }}/serial

- name: Send root.cnf
  template:
    src: root.cnf.j2
    dest: "{{ ca_path }}/root.cnf"

- name: Create rootCA.key
  openssl_privatekey:
    path: "{{ ca_path }}/rootCA.key"

- name: Create rootCA.pem
  command: openssl req -x509 -new -nodes -key {{ ca_path }}/rootCA.key -extensions v3_ca -sha256 -days {{ expiration_days }} -out {{ ca_path }}/rootCA.pem -subj "/CN={{ common_name }}" -config {{ ca_path }}/root.cnf

- name: Create certificates requests for all services
  command: openssl req -out {{ ca_path }}/{{ item.name }}/{{ item.name }}.csr -newkey rsa:{{ rsa_key_length }} -nodes -keyout {{ ca_path }}/{{ item.name }}/{{ item.name }}.key -config {{ ca_path }}/root.cnf -subj "/C={{ country }}/ST={{ state }}/L={{ locality }}/O={{ organization }}/OU={{ organizational_unit }}/CN={{ item.name }}" -extensions {{ item.name }}
  with_items: "{{ services }}"

- name: Sign certificates
  expect:
    command: openssl ca -extensions {{ item.name }} -days {{ expiration_days }} -notext -md sha256 -in {{ ca_path }}/{{ item.name }}/{{ item.name }}.csr -out {{ ca_path }}/{{ item.name }}/{{ item.name }}.crt -cert {{ ca_path }}/rootCA.pem -keyfile {{ ca_path }}/rootCA.key -config {{ ca_path }}/root.cnf
    responses:
      "Sign the certificate?": "y"
      "1 out of 1 certificate requests certified, commit?": "y"
  with_items: "{{ services }}"

- name: Convert to pkcs12
  command: openssl pkcs12 -export -in {{ ca_path }}/{{ item.name }}/{{ item.name }}.crt -inkey {{ ca_path }}/{{ item.name}}/{{ item.name }}.key -out {{ ca_path }}/{{ item.name }}/{{ item.name }}.p12 -name "{{ item.name }}" -passout pass:{{ keystore_password }}
  with_items: "{{ services }}"

- name: Add to keystore
  command: keytool -importkeystore -destkeystore {{ ca_path }}/{{ keystore_name }} -deststorepass {{ keystore_password }} -srckeystore {{ ca_path }}/{{ item.name }}/{{ item.name }}.p12 -srcstoretype PKCS12 -srcstorepass {{ keystore_password }}
  with_items: "{{ services }}"

- name: Copy baltimore.ca.cert
  copy:
    src: trusted-certificates/crt/baltimore.ca.cert
    dest: "{{ ca_path }}/baltimore.ca.cert"

- name: Import CA's to the truststore
  command: keytool -import -file {{ ca_path }}/{{ item }} -alias {{ item }} -keystore {{ ca_path }}/{{ truststore_name }} -noprompt -v -storepass {{ keystore_password }}
  with_items:
    - rootCA.pem
    - baltimore.ca.cert

- name: Convert from jks to pkcs12 store
  shell: keytool -importkeystore -srckeystore {{ ca_path }}/{{ item }} -destkeystore {{ ca_path }}/{{ item }}.p12 -deststoretype pkcs12 -srcstorepass {{ keystore_password }} -deststorepass {{ keystore_password }}
  with_items:
    - "{{ keystore_name }}"
    - "{{ truststore_name }}"